import {
    type Generated,
    type Insertable,
    type Selectable,
    type Updateable
} from 'kysely'

export interface Database {
    genres: GenresTable
}

export interface GenresTable {
    // Columns that are generated by the database should be marked
    // using the `Generated` type. This way they are automatically
    // made optional in inserts and updates.
    id: Generated<string>
    name: string
}

export type Genre = Selectable<GenresTable>
export type NewGenre = Insertable<GenresTable>
export type GenreUpdate = Updateable<GenresTable>
